# Generated by Django 3.1 on 2020-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfo1',
            name='value',
            field=models.CharField(max_length=10, verbose_name='value'),
        ),
    ]
