# Generated by Django 3.1 on 2020-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0002_auto_20200813_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfo1',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
    ]
