# Generated by Django 3.1 on 2020-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0003_auto_20200813_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo1',
            name='a',
            field=models.IntegerField(default=0, verbose_name='a'),
            preserve_default=False,
        ),
    ]
