# Generated by Django 3.1 on 2020-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0004_bioinfo1_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo1',
            name='c',
            field=models.FloatField(default=0, verbose_name='c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo1',
            name='g',
            field=models.FloatField(default=0, verbose_name='g'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo1',
            name='gc',
            field=models.FloatField(default=0, verbose_name='gc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo1',
            name='t',
            field=models.FloatField(default=0, verbose_name='t'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bioinfo1',
            name='a',
            field=models.FloatField(verbose_name='a'),
        ),
    ]
