# Generated by Django 3.1 on 2020-08-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0005_auto_20200814_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfo1',
            name='a',
            field=models.FloatField(default=0.0, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='bioinfo1',
            name='c',
            field=models.FloatField(default=0.0, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='bioinfo1',
            name='g',
            field=models.FloatField(default=0.0, verbose_name='g'),
        ),
        migrations.AlterField(
            model_name='bioinfo1',
            name='gc',
            field=models.FloatField(default=0.0, verbose_name='gc'),
        ),
        migrations.AlterField(
            model_name='bioinfo1',
            name='t',
            field=models.FloatField(default=0.0, verbose_name='t'),
        ),
    ]
