# Generated by Django 3.1 on 2020-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0007_auto_20200814_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfo1',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
