# Generated by Django 3.1 on 2020-08-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0008_auto_20200814_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfo1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
