# Generated by Django 3.1 on 2020-08-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0010_auto_20200816_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioinfo1',
            options={},
        ),
    ]
