# Generated by Django 3.1 on 2020-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfo1', '0011_auto_20200816_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo1',
            name='isVisible',
            field=models.BooleanField(default=False, verbose_name='isVisible'),
            preserve_default=False,
        ),
    ]
